version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot*"
          - "io.spring*"
      webjars:
        patterns:
          - "org.webjars*"
      testcontainers:
        patterns:
          - "org.testcontainers*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
